### PR TITLE
Add UML Activity Diagram

### PR DESCRIPTION
**Pull request by gboeker**

### CODE REVIEW

**Comment by shriyakalakata** [comment]
I think after the new user fills out player information, it should point to "looking for someone to play with?"

What do you think?

**Comment by iltenahmet** [comment]
lgtm

**Review by iltenahmet — APPROVED** [review]
lgtm

**Comment by shriyakalakata** [comment]
I like the diagram but two things:
1. I think we should create the diagram on an online platform like Figma
2. Each UML diagram should be specific to a user story

**Pull request merged**
